"""Add extended project fields

Revision ID: 097fcd958896
Revises: ae9defc05486
Create Date: 2026-05-14 22:32:49.842088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097fcd958896'
down_revision: Union[str, None] = 'ae9defc05486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total_cost_approved', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('cost_used', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('project_code', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('expected_completion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(), server_default='Active', nullable=False))
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'expected_completion_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'project_code')
    op.drop_column('projects', 'client_name')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'cost_used')
    op.drop_column('projects', 'total_cost_approved')
    # ### end Alembic commands ###
