"""Add_is_active_and_created_by_id_to_User

Revision ID: 335ec1438308
Revises: 415ae082e12c
Create Date: 2026-05-16 07:19:17.825277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335ec1438308'
down_revision: Union[str, None] = '415ae082e12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET is_active = 1")
    op.alter_column('users', 'is_active', nullable=False)
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by_id')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
