"""add task_type and key_index to tasks

Revision ID: 415ae082e12c
Revises: 6da44d037093
Create Date: 2026-05-16 05:16:37.104043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415ae082e12c'
down_revision: Union[str, None] = '6da44d037093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    task_type_enum = sa.Enum('task', 'bug', 'story', 'epic', name='tasktype')
    task_type_enum.create(op.get_bind())
    op.add_column('tasks', sa.Column('task_type', task_type_enum, nullable=False, server_default='task'))
    op.add_column('tasks', sa.Column('key_index', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('story_points', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'story_points')
    op.drop_column('tasks', 'key_index')
    op.drop_column('tasks', 'task_type')
    sa.Enum(name='tasktype').drop(op.get_bind())
    # ### end Alembic commands ###
