"""add created_by_id to tasks

Revision ID: 6da44d037093
Revises: be3ac2340bf0
Create Date: 2026-05-16 04:58:43.551435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da44d037093'
down_revision: Union[str, None] = 'be3ac2340bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by_id')
    # ### end Alembic commands ###
