"""Add tasks comments and rewards

Revision ID: be3ac2340bf0
Revises: 097fcd958896
Create Date: 2026-05-14 23:14:48.022754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3ac2340bf0'
down_revision: Union[str, None] = '097fcd958896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_id'), 'task_comments', ['id'], unique=False)
    op.add_column('projects', sa.Column('rewards_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('is_reviewed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('reward_points', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_reward_points', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_reward_points')
    op.drop_column('tasks', 'reward_points')
    op.drop_column('tasks', 'is_reviewed')
    op.drop_column('projects', 'rewards_enabled')
    op.drop_index(op.f('ix_task_comments_id'), table_name='task_comments')
    op.drop_table('task_comments')
    # ### end Alembic commands ###
